---
name: Build regular LinkAce Docker image

on:
  push:
    tags:
      - "*"
    branches:
      - dev-v2
jobs:
  build_regular_docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=linkace/linkace
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push advanced image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/dockerfiles/release-multiplatform.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.prep.outputs.tags }}

      - name: Prepare simple build tags
        id: prep-simple
        run: |
          DOCKER_IMAGE=linkace/linkace
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION}-php-nginx,${DOCKER_IMAGE}:php-nginx,${DOCKER_IMAGE}:${VERSION}-simple,${DOCKER_IMAGE}:simple"
          echo ::set-output name=tags::${TAGS}

      - name: Build and push simple image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/dockerfiles/release-multiplatform-simple.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.prep-simple.outputs.tags }}
